### Creat empty array

In [10]:
import numpy as np
df =np.empty(0)
df

array([], dtype=float64)

### create 1D Array

In [12]:
num = [1,2,3]
num = np.array(num)
print('1d array:',num)

1d array: [1 2 3]


### creat 2D array

In [16]:
num2=[[1,2,3],[4,5,6]]
num2 = np.array(num2)
print("\n2d array:",num2)


2d array: [[1 2 3]
 [4 5 6]]


In [18]:
num3 =[[1,2,3,],[4,5,6],[7,8,9]]
num3 = np.array(num3)
print("\n3d array:",num3)


3d array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


### 5 zeroos

In [ ]:
arr = np.zeros(5)
print('single array',)