### Example code for initializing NumPy array

In [8]:
import numpy as np
import pandas as pd
#create a rank 1 array
a=np.array([0,1,2])
print(a)
a.dtype

[0 1 2]


dtype('int32')

In [17]:
a.shape

(3,)

In [20]:
#this will print the dimension of the array
a[0]
a[1]
a[2]

2

In [22]:
#change an element of the array
a[0] =5
a

array([5, 1, 2])

In [23]:
#create a rank 2 array
b=np.array([[0,2,3],[3,4,5]])
b.shape

(2, 3)

In [24]:
b

array([[0, 2, 3],
       [3, 4, 5]])

In [26]:
b[0,0],
b[0,1],

(2,)

### create numpy array

In [ ]:
# create